#!/usr/bin/env Rscript
file<-sub("^--file=","",grep("^--file=",commandArgs(FALSE),value=TRUE)[1]);root<-normalizePath(file.path(dirname(file),".."))
source(file.path(root,"R/lib/common.R"));source(file.path(root,"R/lib/contract.R"));source(file.path(root,"R/lib/calibration.R"))
checks<-0L
check<-function(ok,label){if(!isTRUE(ok))stop("FAIL: ",label);checks<<-checks+1L;cat("PASS:",label,"\n")}
fails<-function(expr)inherits(tryCatch(force(expr),error=function(e)e),"error")
cfg<-read_study_config(file.path(root,"config/study.yml"));check(cfg$populations$symptom_complete$N==658,"YAML N key remains a named count")
d<-synthetic_data(cfg)
groups<-d[1:4,];groups$cohort<-c("PRONIA","PRONIA","FePsy","NAPLS-3");groups$Studygroup<-c("CHR","ROP",NA,NA)
check(identical(chr_sensitivity_population(groups)$Cases,groups$Cases[c(1,3,4)]),"CHR sensitivity excludes only validated PRONIA ROP records")
check(nrow(chr_sensitivity_population(groups[3:4,]))==2,"external cohorts do not require PRONIA group labels")
for(label in c(NA,"","chr","UNKNOWN")) {
 bad<-groups;bad$Studygroup[1]<-label
 check(fails(chr_sensitivity_population(bad)),paste("invalid PRONIA clinical group rejected:",label))
}
bad<-groups;bad$Studygroup[1]<-"ROP"
check(fails(chr_sensitivity_population(bad)),"PRONIA without CHR records is rejected")
tmp_groups<-tempfile(fileext=".csv");write.csv(bad,tmp_groups,row.names=FALSE)
check(fails(canonicalize_data(tmp_groups)),"clinical-group contract is enforced by the input loader");unlink(tmp_groups)
block<-d[1:2,];block[2,]<-block[1,];block$cohort<-"TEST_COHORT";block$COGDIS_score<-c(2,5)
correction<-list(cohort="TEST_COHORT",key_sha256=digest::digest(as.character(block$Cases[1]),algo="sha256",serialize=FALSE),field="COGDIS_score",conflicting_values=c(2,5),retained_value=5)
check(fails(reconcile_rows(block)),"undocumented duplicate is rejected")
z<-reconcile_rows(block,correction);check(nrow(z)==1&&z$COGDIS_score==5,"identified duplicate retains the externally specified value")
check(identical(reconcile_rows(block[2:1,],correction),z),"duplicate resolution is independent of row order")
check(identical(reconcile_rows(z),z),"unique resolved input needs no correction record")
bad<-block;bad$Mean_Score[2]<-99;check(fails(reconcile_rows(bad,correction)),"fixed-prediction disagreement rejected")
bad<-block;bad$age[2]<-99;check(fails(reconcile_rows(bad,correction)),"additional clinical disagreement rejected")
bad<-block;bad$Cases<-"OTHER_PERSON";check(fails(reconcile_rows(bad,correction)),"unrelated duplicate cannot receive the correction")
bad<-block;bad$cohort<-"OTHER_COHORT";check(fails(reconcile_rows(bad,correction)),"correction is specific to its cohort")
bad<-block;bad$COGDIS_score[1]<-3;check(fails(reconcile_rows(bad,correction)),"unrecognized conflicting values rejected")
bad<-bind_rows(block,block);check(fails(reconcile_rows(bad,correction)),"more than two duplicate rows rejected")
bad<-bind_rows(block,mutate(block,Cases="SECOND_PERSON"));check(fails(reconcile_rows(bad,correction)),"a second duplicated participant cannot share one correction")
for(field in c("Cases","cohort","EXP_LABEL","PRED_LABEL","Mean_Score","Probs_platt","BrainAGE_SBC_corr","Comp1")) {
  wrong<-correction;wrong$field<-field
  check(fails(reconcile_rows(block,wrong)),paste("correction cannot target fixed field",field))
}
wrong<-correction;wrong$conflicting_values<-c(2,2);check(fails(reconcile_rows(block,wrong)),"correction values must be distinct")
wrong<-correction;wrong$retained_value<-7;check(fails(reconcile_rows(block,wrong)),"retained value must be observed")
wrong<-correction;wrong$conflicting_values[1]<-NA;check(fails(reconcile_rows(block,wrong)),"missing correction value rejected")
wrong<-correction;wrong$field<-NULL;check(fails(reconcile_rows(block,wrong)),"incomplete correction schema rejected")
wrong<-correction;wrong$key_sha256<-c(wrong$key_sha256,wrong$key_sha256);check(fails(reconcile_rows(block,wrong)),"nonscalar correction identity rejected")
other<-block;other$COGDIS_score<-2;other$age<-c(21,22);other$cohort<-"ANOTHER_COHORT"
other_record<-correction;other_record$field<-"age";other_record$cohort<-"ANOTHER_COHORT";other_record$conflicting_values<-c(21,22);other_record$retained_value<-21
check(nrow(reconcile_rows(other,other_record))==1&&reconcile_rows(other,other_record)$age==21,"metadata selects another clinical field, cohort and first value")
tmp<-tempfile(fileext=".csv");block$sips_p_z<-c(-1,1);write.csv(block,tmp,row.names=FALSE)
record_path<-tempfile(fileext=".json");jsonlite::write_json(correction,record_path,auto_unbox=TRUE)
clean<-canonicalize_data(tmp,correction=jsonlite::read_json(record_path,simplifyVector=TRUE));unlink(c(tmp,record_path))
check(nrow(clean)==1&&clean$COGDIS_score==5&&!"sips_p_z"%in%names(clean),"JSON correction and stale-scale removal work through the input loader")
check(fails(strict_binary(c(0,1,.8))),"nonbinary numerical outcome cannot be truncated")
check(identical(strict_binary(factor(c("0","1"))),c(0L,1L)),"factor outcome uses its labels")
x<-data.frame(a=c(0,2,100),b=c(1,3,NA));cc<-x[complete.cases(x),];sc<-scale_fit(cc,c("a","b"),"test")
check(abs(mean(sc$data$a_z))<1e-14&&sc$params$mean[1]==1,"complete population precedes scaling")
check(fails(scale_fit(x,c("a","b"),"bad")),"scaling incomplete population rejected")
matched<-sc$data[,c("a","a_z")];check(identical(matched$a_z,sc$data$a_z),"matched model uses shared-variable scaling")
for(w in c(.15,.2,.25,.3)) {
 g<-window_grid(c(0,1),w,w/4)
 check(in_window(1,g,nrow(g))&&tail(g$end,1)==1,paste("maximum covered at width",w))
 check(in_window(g$start[1],g,1)&&!in_window(g$end[1],g,1),paste("half-open endpoints at width",w))
 check(all(vapply(seq(0,1,length.out=101),function(v)any(vapply(seq_len(nrow(g)),function(i)in_window(v,g,i),logical(1))),logical(1))),paste("no range holes at width",w))
}
g<-window_grid(rep(4,8));check(nrow(g)==1&&g$right_closed&&all(in_window(rep(4,8),g,1)),"constant range is one closed interval")
check(nrow(window_grid(c(NA,Inf)))==0,"empty finite range returns empty grid")
check(fails(window_grid(0:1,0,.05)),"invalid width rejected")
check(auc_fast(rep(1,4),c(0,0,1,1))==.5,"ties have half credit")
check(is.na(auc_fast(1:5,rep(0,5))),"zero-class AUC is undefined")
for(i in 1:25){set_replicate_seed("singleton",i);check(identical(permute_within(c(99,3,5),c("single","pair","pair"))[1],99),paste("singleton permutation",i))}
b<-bootstrap_auc(c(-1,-.5,2),c(0,0,1),"single_positive",20)
check(b['valid']==20&&b['lo']==1&&b['hi']==1,"singleton class bootstrap samples positions, not 1:index")
z<-tibble(EXP_LABEL=c(0,1,0,1),Mean_Score=c(0,1,NA,2),mod=c(0,0,0,0),cohort="PRONIA")
w<-window_stats_1d(z,"mod",min_events=1,min_non_events=1)
check(w$rows$N==3&&w$rows$events==2&&w$rows$non_events==1,"support and AUC use one finite-case mask")
z$mod2<-z$mod;surf<-surface_stats(z,"mod","mod2",min_events=1,min_non_events=1)
check(surf$rows$N==3&&surf$rows$events==2,"2D support shares finite-case mask")
ns<-null_summary(c(1,2,NA,Inf),1.5,"invalid","test","upper")
check(ns$attempted==4&&ns$valid==2&&ns$invalid==2&&ns$exceedances==1&&ns$p_add_one==2/3&&ns$method_review_required,"invalid null draws counted; correct add-one denominator and method flag")
check(is.na(null_summary(c(NA,Inf),1,"none","test","upper")$p_add_one),"all-invalid null returns no p value")
fun<-function(i)c(runif(3),rnorm(2),sample.int(10,3))
a<-deterministic_rows(12,"streams",fun,1);b<-deterministic_rows(12,"streams",fun,2,order=12:1)
check(identical(a,b),"serial/parallel/reversed scheduling produces identical draws")
check(!identical(a,deterministic_rows(12,"other_stream",fun,1)),"analysis IDs use distinct streams")
st<-stream_states("streams",2);check(identical(st[[2]],parallel::nextRNGStream(st[[1]])),"replicates use actual nextRNGStream states")
y<-rep(c(0,1,0,0,1),20);p<-plogis(seq(-1,1,length.out=length(y)))
o<-calibration_bootstrap(y,p,12,"cal_same","original");a<-calibration_bootstrap(y,p,12,"cal_same","apparent_slope");h<-calibration_bootstrap(y,p,12,"cal_same","heldout_fixed")
check(identical(o$draws,h$draws),"original and fixed held-out assessments do not refit updates")
check(any(abs(o$draws[,'Brier']-a$draws[,'Brier'])>1e-6),"apparent bootstrap refits the update")
check(sd(a$draws[,'updating_alpha'],na.rm=TRUE)>0,"update parameters vary across apparent bootstrap draws")
check(all(abs(a$draws[,'alpha'][is.finite(a$draws[,'alpha'])])<1e-4),"post-update assessment distinguished from updating parameters")
check(identical(segment_support(c(TRUE,TRUE,FALSE,TRUE,TRUE)),c(1L,1L,2L,3L,3L)),"support hole splits model-grid ribbon groups")
# Driver imports are inert, even if commandArgs() belongs to this test.
e<-new.env();source(file.path(root,"R/run_analysis.R"),local=e);check(exists("pipeline_main",e)&&!exists("d",e,inherits=FALSE),"source driver does not read data or fit")
check(is.na(window_stats_1d(z[FALSE,],"mod")$Dmax),"empty eligible 1D population is explicitly unestimable")
check(is.na(surface_stats(z[FALSE,],"mod","mod2")$Dmax),"empty eligible 2D population is explicitly unestimable")
cat("TOTAL",checks,"production assertions passed\n")
