#!/usr/bin/env Rscript
args<-commandArgs(TRUE);if(length(args)!=1)stop("Supply computed run directory")
r<-normalizePath(args[1]);manifest<-jsonlite::read_json(file.path(r,"run_manifest.json"));stopifnot(manifest$mode%in%c("synthetic","full"))
if(!is.null(manifest$render_status))stopifnot(identical(manifest$render_status,"COMPLETE"))
config<-yaml::read_yaml(file.path(r,"consumed_study.yml"))
expected_N<-if(manifest$mode=="synthetic")5L*config$synthetic$participants_per_cohort else sum(vapply(config$cohorts,function(z)z$N,numeric(1)))
read<-function(folder,name)read.csv(file.path(r,folder,paste0(name,".csv")),check.names=FALSE)
n<-0L;check<-function(x,msg){stopifnot(isTRUE(x));n<<-n+1L;cat("PASS:",msg,"\n")}
check(nrow(read("tables","global_1d_landscape_tests"))==6,"six primary 1D moderators")
check(nrow(read("tables","global_2d_surface_tests"))==6,"six primary 2D pairs")
a<-read("tables","table_S5_component_landscape_associations")
check(nrow(a)==288&&all(table(a$correction_family)==24),"full 288 associations; 12 complete BH families")
check(nrow(read("tables","component_selected_statistic_key"))==48,"all 12 contexts and four components in S4")
co<-read("tables","canonical_glm_coefficients")
check(length(unique(co$model_id))==9,"eight hierarchy fits plus matched comparison")
check(nrow(read("tables","glm_hierarchy"))==6,"all six declared nested comparisons")
check(all(read("tables","glm_hierarchy")$same_rows),"nested model comparisons use identical observations")
models<-readRDS(file.path(r,"private/canonical_glm_models.rds"));grid<-read("figure_data","canonical_linear_moderation_curve")
p<-predict(models$GLM_M1_CANONICAL,grid,type="response")
check(all(grid$reference_cohort=="NAPLS-3")&&max(abs(p-grid$probability))<1e-12,"Figure 4 grid uses exact canonical model and reference")
ids<-readRDS(file.path(r,"private/model_row_ids.rds"));check(identical(ids$functioning,ids$matched),"functioning and matched fits share row identities")
check(nrow(read("tables","gam_bounded_diagnostic_sensitivity"))==28,"four GAM specifications with all seven terms")
seg<-read("figure_data","gam_sips_n_uncertainty_segmented")
check(all(vapply(split(seg$supported_region,seg$segment_id),function(z)length(unique(z))==1,logical(1))),"GAM support groups never bridge a hole")
registry<-read("tables","resampling_validity_registry")
check(all(registry$attempted==registry$valid+registry$invalid),"all resampling counts reconcile")
null<-registry[registry$extreme_applicable%in%TRUE & is.finite(registry$p_add_one),]
check(max(abs(null$p_add_one-(1+null$extreme)/(1+null$valid)))<1e-14,"add-one denominator matches recorded valid draws")
cal<-read("tables","external_calibration_original_vs_apparent_bootstrap")
check(all(cal$attempted[cal$metric=="Brier"]==manifest$resamples$pooled_calibration_bootstrap),"calibration count labelled with actual replicates")
one<-read("figure_data","primary_1d_window_details_figure_ready")
plotted<-read("figures/plotted_values","primary_1d_landscape_six_panel")
check(identical(one$AUC_bootstrap_lo,plotted$AUC_bootstrap_lo)&&identical(one$AUC_bootstrap_hi,plotted$AUC_bootstrap_hi),"Figure 1 ribbons use computed percentile bounds")
check(all(abs(one$center-(one$start+one$end)/2)<1e-10),"Figure 1 coordinates are window midpoints")
surf<-read("figure_data","primary_2d_cell_details");plot_surf<-read("figures/plotted_values","sips_n_brainage_local_auc_surface")
check(identical(surf$AUC[surf$pair=="brainage_sbc_x_sips_n"],plot_surf$AUC),"Figure 2 exports every supported AUC without censoring")
if(identical(manifest$anatomy_figures,"GENERATED_FROM_EXTERNAL_ASSETS")) {
yeo<-read("figure_data/yeo","yeo_radar_display")
check(nrow(yeo)==108&&length(unique(yeo$network_order))==27,"Figure 3 retains 27 ordered regions and four identities")
check(max(abs(yeo$network_occupancy_percent-100*yeo$component_overlap_voxels/yeo$network_roi_voxels))<1e-10,"Figure 3 radar uses recorded ROI voxel denominator")
}
expected_figures<-if(identical(manifest$anatomy_figures,"GENERATED_FROM_EXTERNAL_ASSETS"))9L else 7L
check(length(list.files(file.path(r,"figures"),pattern="[.]pdf$"))==expected_figures,"all requested figures generated")
check(nrow(read("tables","landscape_population_sensitivity_1d_all_six"))==54,"nine population sensitivities cover all six moderators")
check(nrow(read("tables","window_support_sensitivity_1d_all_six"))==12,"both support settings cover all six moderators")
sex<-read("tables","sex_stratified_performance")
check(nrow(sex)==2&&sum(sex$N)==expected_N,"descriptive sex strata partition the declared participant population")
if(identical(manifest$anatomy_figures,"GENERATED_FROM_EXTERNAL_ASSETS")) {
aal<-read("figure_data/aal3","aal3_recorded_full_overlap")
check(max(abs(aal$occupancy_percent[aal$ROI_voxels>0]-100*aal$overlap_voxels[aal$ROI_voxels>0]/aal$ROI_voxels[aal$ROI_voxels>0]))<1e-10&&all(is.na(aal$occupancy_percent[aal$ROI_voxels==0])),"AAL3 voxel denominator preserved; absent parcels remain undefined")
}
check(all(c("LR_pos","LR_neg")%in%names(read("tables","primary_validation"))),"likelihood ratios retained")
cat("TOTAL",n,"computed-output assertions passed\n")
